return function(palette)
	return {
		Normal = { fg = palette.white, bg = palette.bg },
		NormalNC = { bg = palette.bg },
		StatusLine = { fg = palette.bg, bg = palette.white },
		StatusLineNC = { fg = palette.bg, bg = palette.dark_grey },
		WinSeparator = { fg = palette.white, bg = palette.bg },
		EndOfBuffer = { fg = palette.bg },

		Keyword = { fg = palette.white },
		Constant = { fg = palette.light_grey },
		String = { fg = palette.grey },
		Comment = { fg = palette.dark_grey },
		Number = { fg = palette.white, bold = true },
		Error = { fg = palette.white, bg = palette.darker_red },
		Search = { bg = palette.darker_grey },
		Visual = { bg = palette.darker_grey },

		Boolean = { link = "Normal", bold = true },
		Delimiter = { link = "Normal" },
		Identifier = { link = "Normal" },
		Title = { link = "Normal" },
		Debug = { link = "Normal" },
		Exception = { link = "Normal" },
		FoldColumn = { link = "Normal" },
		Macro = { link = "Normal" },
		ModeMsg = { link = "Normal" },
		MoreMsg = { link = "Normal" },
		Question = { link = "Normal" },
		Conditional = { link = "Keyword" },
		Statement = { link = "Keyword" },
		Operator = { link = "Keyword" },
		Structure = { link = "Keyword" },
		Function = { link = "Keyword" },
		Include = { link = "Keyword" },
		Type = { link = "Keyword" },
		Typedef = { link = "Keyword" },
		Todo = { link = "Keyword" },
		Label = { link = "Keyword" },
		Define = { link = "Keyword" },
		DiffAdd = { link = "Keyword" },
		diffAdded = { link = "Keyword" },
		diffCommon = { link = "Keyword" },
		Directory = { link = "Keyword" },
		PreCondit = { link = "Keyword" },
		PreProc = { link = "Keyword" },
		Repeat = { link = "Keyword" },
		Special = { link = "Keyword" },
		SpecialChar = { link = "Keyword" },
		StorageClass = { link = "Keyword" },
		SpecialComment = { link = "String" },
		CursorLineNr = { link = "String" },
		Character = { link = "Number" },
		Float = { link = "Number" },
		Tag = { link = "Number" },
		Folded = { link = "Number" },
		WarningMsg = { link = "Number" },
		Added = { fg = palette.white },
		Changed = { fg = palette.dark_red },

		CmpItemKindDefault = { fg = palette.light_grey },

		MiniPickPrompt = { fg = palette.red },
		MiniPickMatchRanges = { fg = palette.red },
		MiniClueBorder = { fg = palette.dark_red },
		MiniClueSeparator = { fg = palette.darker_red },
		MiniClueNextKey = { fg = palette.red },
		MiniClueNextKeyWithPostKeys = { fg = palette.dark_red },

		["@text"] = { link = "Normal" },
		["@text.strong"] = { fg = palette.white, bold = true },
		["@text.emphasis"] = { fg = palette.white, italic = true },
		["@text.underline"] = { link = "Normal", underline = true },
		["@text.strike"] = { fg = palette.dark_grey, strikethrough = true },
		["@text.title"] = { link = "Keyword" },
		["@text.literal"] = { link = "String" },
		["@text.uri"] = { link = "String", underline = true },
		["@comment"] = { link = "Comment" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Constant" },
		["@constant.macro"] = { link = "Constant" },
		["@string"] = { link = "String" },
		["@string.regex"] = { link = "String" },
		["@string.escape"] = { link = "String" },
		["@character"] = { link = "Number" },
		["@number"] = { link = "Number" },
		["@boolean"] = { link = "Normal" },
		["@float"] = { link = "Number" },
		["@function"] = { link = "Keyword" },
		["@function.builtin"] = { link = "Keyword" },
		["@function.macro"] = { link = "Keyword" },
		["@method"] = { link = "Keyword" },
		["@constructor"] = { link = "Keyword" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { link = "Keyword" },
		["@keyword.operator"] = { link = "Keyword" },
		["@operator"] = { link = "Keyword" },
		["@punctuation.delimiter"] = { link = "Normal" },
		["@punctuation.bracket"] = { link = "Normal" },
		["@punctuation.special"] = { link = "Normal" },
		["@tag"] = { link = "Number" },
		["@tag.attribute"] = { link = "Constant" },
		["@tag.delimiter"] = { link = "Normal" },
		["@type"] = { link = "Keyword" },
		["@type.builtin"] = { link = "Keyword" },
		["@variable"] = { link = "Normal" },
		["@variable.builtin"] = { link = "Keyword" },
		["@variable.parameter"] = { link = "Normal" },
		["@property"] = { link = "Normal" },
		["@field"] = { link = "Normal" },
		["@namespace"] = { link = "Keyword" },
		["@module"] = { link = "Keyword" },
		["@label"] = { link = "Keyword" },
		["@diff.plus"] = { link = "Added" },
		["@diff.minus"] = { fg = palette.red },
		["@diff.delta"] = { link = "Changed" },
	}
end
